name: Pull Updated Prices

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 6 1 * *'
  workflow_dispatch:

jobs:
  Pull-Prices:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.0'
      - shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
          ZENODO_RECORD_ID: ${{ secrets.ZENODO_RECORD_ID }}
          ZENODO_PUBLISH: publish
        run: |
          go run collect.go